name: Linux Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    steps:
    - uses: actions/checkout@v2
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
    - name: Checkout submodules
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - name: Install dependencies
      shell: bash
      run: |
          sudo apt install -y verilator libgmp-dev libmpfr-dev libmpc-dev iverilog python3-pip python3-setuptools
          verilator --version
    - name: Install pono
      shell: bash
      env: 
          CC: gcc-8
          CXX: g++-8
      run: |
          wget https://github.com/rdaly525/coreir/releases/download/v0.1.50/coreir-linux.tar.gz
          tar -xzf coreir-linux.tar.gz
          cd coreir-linux
          sudo make install 
          cd ../
          sudo pip3 install Cython==0.29 --install-option="--no-cython-compile"
          git clone https://github.com/upscale-project/pono
          cd pono
          ./travis-scripts/setup-msat.sh --auto-yes
          ./contrib/setup-bison.sh
          ./contrib/setup-flex.sh
          ./contrib/setup-btor2tools.sh
          ./travis-scripts/download-cvc4.sh
          ./contrib/setup-smt-switch.sh --with-msat --cvc4-home=./deps/CVC4 --python
          sudo pip3 install -e ./deps/smt-switch/build/python
          ./configure.sh --with-msat --python --with-coreir-extern
          cd build && make -j2 && make test && cd ../
          sudo pip3 install -e ./build/python
          cd ..

    - name: Install Python packages
      shell: bash -l {0}
      run: |
          sudo pip3 install "pytest<6"
          sudo pip3 install pytest-cov pytest-pycodestyle
          sudo pip3 install mantle>=2.0.0  # for tests.common
          sudo pip3 install vcdvcd decorator kratos
          sudo pip3 install .

    - name: Pytest
      shell: bash -l {0}
      run: |
        pytest --pycodestyle --cov-report=xml --cov=fault tests/ -v -r s
    - name: Coverage
      shell: bash -l {0}
      run: |
        bash <(curl -s https://codecov.io/bash)

